
export const INCREMENT = 'INCREMENT'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const UPDATE_SELECT_FILTER = 'UPDATE_SELECT_FILTER'
export const UPDATE_DATE_RANGE_FILTER = 'UPDATE_DATE_RANGE_FILTER'