export default {
  en: {
    'choose-language': 'Choose language',
    'form-username': 'Username',
    'form-user': 'User',
    'form-comment': 'Comment',
    'nav-counter': 'Counter',
    'nav-filters': 'Filters',
    'nav-articles': 'Articles',
    'nav-comments': 'Сomments',
    'counter-increment': 'Increment',
    'select-article': 'Please select an article',
    'loading': 'Loading...',
    'show-comments': 'Show comments',
    'hide-comments': 'Hide comments',
    'delete-article': 'Delete',
    'no-comments': 'No comments yet',
  },
  ru: {
    'choose-language': 'Выберите язык',
    'form-username': 'Имя пользователя',
    'form-user': 'Пользователь',
    'form-comment': 'Комментарий',
    'nav-counter': 'Счётчик',
    'nav-filters': 'Фильтры',
    'nav-articles': 'Статьи',
    'nav-comments': 'Комментарии',
    'counter-increment': 'Прибавить',
    'select-article': 'Пожалуйста, выберите статью',
    'loading': 'Загрузка...',
    'show-comments': 'Показать комментарии',
    'hide-comments': 'Скрыть комментарии',
    'delete-article': 'Удалить',
    'no-comments': 'Ещё никто не оставил комментарий',
  },
};